// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAPIBaseURL():Promise<string>;

export function SelectDirectory(arg1:string):Promise<string>;
