// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AbortModelWrite(arg1:string):Promise<Record<string, any>>;

export function AppendModelWriteChunk(arg1:string,arg2:string):Promise<Record<string, any>>;

export function BeginModelWrite(arg1:string):Promise<Record<string, any>>;

export function CommitModelWrite(arg1:string):Promise<Record<string, any>>;

export function GetAPIBaseURL():Promise<string>;

export function SelectDirectory(arg1:string):Promise<string>;

export function WriteModelFile(arg1:string,arg2:string):Promise<Record<string, any>>;
