// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AbortModelWrite(arg1) {
  return window['go']['main']['App']['AbortModelWrite'](arg1);
}

export function AppendModelWriteChunk(arg1, arg2) {
  return window['go']['main']['App']['AppendModelWriteChunk'](arg1, arg2);
}

export function BeginModelWrite(arg1) {
  return window['go']['main']['App']['BeginModelWrite'](arg1);
}

export function CommitModelWrite(arg1) {
  return window['go']['main']['App']['CommitModelWrite'](arg1);
}

export function GetAPIBaseURL() {
  return window['go']['main']['App']['GetAPIBaseURL']();
}

export function SelectDirectory(arg1) {
  return window['go']['main']['App']['SelectDirectory'](arg1);
}

export function WriteModelFile(arg1, arg2) {
  return window['go']['main']['App']['WriteModelFile'](arg1, arg2);
}
